// Generates src/abi/<camelName>.ts from Foundry artifacts in ../out. Run `forge build` first.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', '..', 'out');
const dest = join(here, '..', 'src', 'abi');
mkdirSync(dest, { recursive: true });

const targets = [
  ['VigilSessionOracle.sol/VigilSessionOracle.json', 'vigilSessionOracle'],
  ['VigilRiskEngine.sol/VigilRiskEngine.json', 'vigilRiskEngine'],
  ['VigilOracle.sol/VigilOracle.json', 'vigilOracle'],
  ['VigilBackstop.sol/VigilBackstop.json', 'vigilBackstop'],
  ['VigilPremium.sol/VigilPremium.json', 'vigilPremium'],
  ['VigilMigrator.sol/VigilMigrator.json', 'vigilMigrator'],
  ['Morpho.sol/Morpho.json', 'morpho'],
  ['MockFeed.sol/MockFeed.json', 'mockFeed'],
];

for (const [artifact, name] of targets) {
  const { abi } = JSON.parse(readFileSync(join(out, artifact), 'utf8'));
  const keep = abi.filter((i) => i.type === 'function' || i.type === 'error');
  const body = `// Generated by scripts/gen-abi.mjs from out/${artifact} — do not edit.\nexport const ${name}Abi = ${JSON.stringify(keep, null, 2)} as const;\n`;
  writeFileSync(join(dest, `${name}.ts`), body);
  console.log(`wrote src/abi/${name}.ts (${keep.length} items)`);
}
