// Generated by scripts/gen-abi.mjs from out/VigilRiskEngine.sol/VigilRiskEngine.json — do not edit.
export const vigilRiskEngineAbi = [
  {
    "type": "function",
    "name": "EVENT_LEAD_TIME",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EVENT_MAX_LENGTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EVENT_MULT_MAX",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GLOBAL_H_MAX",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "K_MAX_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "L_WEEKEND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DELTA_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_UPDATE_INTERVAL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MULT_MAX",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PREMIUM_MAX_PER_SECOND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PRE_CLOSE_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "RAMP_SECONDS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SESSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IVigilSessionOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TAU_NIGHT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bufferMultiplierWad",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bufferBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "calibrator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closureHaircutBps",
    "inputs": [
      {
        "name": "sf",
        "type": "tuple",
        "internalType": "struct VigilRiskEngine.Surface",
        "components": [
          {
            "name": "sigmaGapWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kTailBps",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "hFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hMaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "L",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "eventMultBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "h",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "eventActive",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ts",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eventMultBpsAt",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ts",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "events",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "from",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "until",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "multBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "guardian",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "haircutBps",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasBufferTable",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasPremiumTable",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "preCloseWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "premiumRefRatePerSecond",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "regime",
        "type": "uint8",
        "internalType": "enum Regime"
      },
      {
        "name": "closureLen",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "prevSurfaces",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "sigmaGapWad",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "kTailBps",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "hFloorBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "hMaxBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "updatedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rampStart",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scheduleEvent",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "e",
        "type": "tuple",
        "internalType": "struct VigilRiskEngine.ScheduledEvent",
        "components": [
          {
            "name": "from",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "until",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "multBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPremiumTables",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct VigilRiskEngine.PremiumTable",
        "components": [
          {
            "name": "lBucket",
            "type": "uint64[4]",
            "internalType": "uint64[4]"
          },
          {
            "name": "rateNoEvent",
            "type": "uint128[4]",
            "internalType": "uint128[4]"
          },
          {
            "name": "rateEvent",
            "type": "uint128[4]",
            "internalType": "uint128[4]"
          }
        ]
      },
      {
        "name": "b",
        "type": "tuple",
        "internalType": "struct VigilRiskEngine.BufferTable",
        "components": [
          {
            "name": "bBps",
            "type": "uint16[6]",
            "internalType": "uint16[6]"
          },
          {
            "name": "multWad",
            "type": "uint128[6]",
            "internalType": "uint128[6]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRoles",
    "inputs": [
      {
        "name": "calibrator_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "guardian_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSurface",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct VigilRiskEngine.Surface",
        "components": [
          {
            "name": "sigmaGapWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kTailBps",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "hFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hMaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "surfaces",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "sigmaGapWad",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "kTailBps",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "hFloorBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "hMaxBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "updatedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "targetHaircutBps",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "AboveGlobalMax",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadEvent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSurface",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadTable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DeltaTooLarge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EventInProgress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LeadTimeTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCalibrator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGuardian",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooFrequent",
    "inputs": []
  }
] as const;
